apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myapp-dev
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/myapp/kustomize/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: myapp-dev
  targetNamespace: dev
