apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: myapp-staging
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/Jackdstp/dstpflux.git
  ref:
    branch: staging
  secretRef:
    name: flux-system
