---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: myapp-prod-semver
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/myapp/kustomize/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: dstpflux-semver
  wait: true
  timeout: 5m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: default
      name: '*'
